version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_Z9yqCNBua2dG@ep-withered-resonance-a1vp6gni-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - DEEPAUTO_API_KEY=oak-bmpbg3je78yymtpderjtwbehf45xjglypqjd
    networks:
      - app-network

  frontend:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
