"""rename routing_payload to routing

Revision ID: 9414b07d68a8
Revises: ee7719966669
Create Date: 2025-07-31 20:15:19.485914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9414b07d68a8'
down_revision: Union[str, Sequence[str], None] = 'ee7719966669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('routing', sa.JSON(), nullable=True))
    op.drop_column('messages', 'routing_payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('routing_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('messages', 'routing')
    # ### end Alembic commands ###
